name: container_tracker
description: Konteyner takip uygulaması - İthalat ve ihracat konteynerleri için OCR tabanlı takip sistemi

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  google_ml_kit: ^0.15.0
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  intl: ^0.19.0
  share_plus: ^7.2.1
  provider: ^6.1.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - images/ 